build-deb:
  image: debian:sid
  stage: build
  before_script:
    - apt-get update > /dev/null
    - apt-get install -y git pkg-config build-essential cmake libliquid-dev libsoapysdr-dev libyaml-cpp-dev libcurlpp-dev libcurl4-gnutls-dev libzmq3-dev libspdlog-dev pybind11-dev libpython3-dev libfmt-dev > /dev/null
    - git clone https://github.com/la1k/libpredict.git
    - cd libpredict
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j4
    - make install
    - cd ../..
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j4
#    - make package
#  artifacts:
#    paths: 
#      - build/*.deb